Repository SalesforceCommerceCloud/sfcc-ci, pull requests merged in 2021-05, with the labels that each got.

#210 Update readme with authorization related details
  README.md
Labels: doc

#207 Update README.md for auth in CLI examples
  README.md
Labels: doc

#198 Added documentation for --json parameter
  README.md
Labels: doc

#183 add ability to use data to read from file with instance:export
  cli.js
  lib/export.js
Labels: cla:signed

#174 Introduce the diff-deployment to sfcc-ci
  README.md
  cli.js
  code_compare_template.html
  index.js
  lib/code.js
  lib/job.js
  lib/log.js
  lib/manifest.js
  lib/webdav.js
  package-lock.json
  package.json
  test/unit/job.js
Labels: dependencies, enhancement

#201 Add JS coverage for the User API methods
  README.md
  index.js
  lib/org.js
  lib/user.js
  test/unit/org.js
  test/unit/user.js
Labels: enhancement

#220 #219 add support to use a resource profile for sandbox creation
  bin/test-cli.sh
  cli.js
  lib/sandbox.js
Labels: enhancement
