Repository SalesforceCommerceCloud/sfcc-ci, pull requests merged in 2022-01, with the labels that each got.

#269 Fix broken colors dependency
  package.json
Labels: dependencies

#267 Add SLAS to javascript API
  README.md
  index.js
Labels: enhancement

#274 Snyk update
  package-lock.json
  package.json
Labels: dependencies

#275 Expose more user properties
  lib/user.js
  test/unit/user.js
Labels: enhancement

#276 Update user with noprompt option regardless of location (AM or ecom)
  cli.js
Labels: bug

#277 Fix cli tests
  bin/test-cli.sh
Labels: bug

#278 Replace istanbul with nyc
  package-lock.json
  package.json
Labels: dependencies

#279 Execute pkg via npx
  package-lock.json
  package.json
Labels: dependencies
