Repository SalesforceCommerceCloud/sfcc-ci, pull requests merged in 2022-11, with the labels that each got.

#318 various SLAS adjustments, added callbackURIs
  README.md
  cli.js
  docs/images/client-api-user.png
  lib/slas.js
Labels: bug

#332 feature #329- reset the user-Update readme file to include reset functionality from JS API
  README.md
Labels: enhancement

#325 removing dependency node-fetch to alleviate snyk issues
  lib/slas.js
  package-lock.json
  package.json
Labels: dependencies

#326 [Snyk] Upgrade snyk from 1.838.0 to 1.986.0
  package-lock.json
  package.json
Labels: cla:signed

#336 User list enhancements
  cli.js
  lib/user.js
  test/unit/user.js
Labels: enhancement
