Repository SalesforceCommerceCloud/sfcc-ci, pull requests merged in 2023-03, with the labels that each got.

#349 [Snyk] Upgrade snyk from 1.1073.0 to 1.1076.0
  package-lock.json
  package.json
Labels: cla:signed

#470 Migrate to @snyk/protect
  package-lock.json
  package.json
Labels: dependencies

#469 Feature/api client auditlogs
  cli.js
  lib/client.js
  lib/org.js
Labels: enhancement

#353 Exposes roles into the APIs level.
  README.md
  lib/role.js
Labels: cla:signed

#473 Add scheduler for Realm and Sandbox
  bin/test-cli.sh
  cli.js
  lib/sandbox.js
Labels: cla:signed
