Repository SalesforceCommerceCloud/sfcc-ci, pull requests merged in 2023-01, with the labels that each got.

#342 [Snyk] Security upgrade jsonwebtoken from 8.5.1 to 9.0.0
  package-lock.json
  package.json
Labels: cla:signed

#343 [Snyk] Upgrade snyk from 1.1064.0 to 1.1066.0
  package-lock.json
  package.json
Labels: cla:signed

#345 Update readme around service user authentication
  README.md
Labels: doc

#350 Oauth client mgmt
  README.md
  bin/test-cli.sh
  cli.js
  lib/auth.js
  lib/client.js
  lib/org.js
  package-lock.json
  package.json
  test/unit/client.js
  test/unit/org.js
Labels: enhancement

#351 Fix failing cli tests
  bin/test-cli.sh
  lib/auth.js
  lib/client.js
  lib/org.js
Labels: bug
